# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesave.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(400, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 371, 41))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 50, 381, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.accounttypeLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.accounttypeLine.setObjectName("accounttypeLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.accounttypeLine)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.websiteURLLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.websiteURLLine.setObjectName("websiteURLLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.websiteURLLine)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.usernameLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameLine.setObjectName("usernameLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.usernameLine)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.passwordLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordLine.setObjectName("passwordLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordLine)
        self.saveButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.saveButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveButton.setObjectName("saveButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.saveButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Save to File"))
        self.label.setText(_translate("Dialog", "Fill in form to save password for online account."))
        self.label_6.setText(_translate("Dialog", "Type of Account:"))
        self.accounttypeLine.setPlaceholderText(_translate("Dialog", "eg. Google Account"))
        self.label_7.setText(_translate("Dialog", "Website login URL:"))
        self.websiteURLLine.setPlaceholderText(_translate("Dialog", "www.example.com/login"))
        self.label_8.setText(_translate("Dialog", "Username or Email:"))
        self.label_9.setText(_translate("Dialog", "Password:"))
        self.saveButton.setText(_translate("Dialog", "Save"))
import res_rc
