# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesave.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(9, 9, 382, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 60, 381, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.websiteURLLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.websiteURLLine.setObjectName("websiteURLLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.websiteURLLine)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.usernameLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameLine.setObjectName("usernameLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.usernameLine)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.passwordLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordLine.setObjectName("passwordLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordLine)
        self.saveButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.saveButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveButton.setObjectName("saveButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.saveButton)
        self.accounttypeLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.accounttypeLine.setObjectName("accounttypeLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.accounttypeLine)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Copy to File"))
        self.label.setText(_translate("Dialog", "Fill in form to save password for online account."))
        self.label_2.setText(_translate("Dialog", "Website login URL: "))
        self.websiteURLLine.setPlaceholderText(_translate("Dialog", "www.example.com/login"))
        self.label_3.setText(_translate("Dialog", "Username or Email:"))
        self.label_4.setText(_translate("Dialog", "Password:"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.accounttypeLine.setPlaceholderText(_translate("Dialog", "eg. Google Account"))
        self.label_5.setText(_translate("Dialog", "Type of Account: "))
